[build]
  publish = "web-version"
  command = ""

[build.environment]
  NODE_VERSION = "18.18.2"

[[redirects]]
  from = "/Sovereign-Coder-Manifesto"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "interest-cohort=()"

[functions]
  directory = "netlify/functions"
